ALTER TABLE conf ADD COLUMN xpub_spending TEXT NOT NULL DEFAULT '';
ALTER TABLE conf ADD COLUMN xpub_donations TEXT NOT NULL DEFAULT '';
ALTER TABLE conf ADD COLUMN xpub_treasury TEXT NOT NULL DEFAULT '';