// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteAuthor } from "./NoteAuthor";

/**
 * A note as returned to its owner (includes private ones) and, for public
 * notes, to everyone else.
 */
export type Note = { id: number, lat: number, lon: number, text: string, public: boolean, author: NoteAuthor, created_at: string, updated_at: string, 
/**
 * Only present on owner responses that asked for `include_deleted=true`.
 */
deleted_at?: string, 
/**
 * Only present on search responses.
 */
distance_km?: number, };
