// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchUserArgs = { 
/**
 * Replacement role set. Omit to leave roles untouched.
 */
roles?: Array<string>, 
/**
 * Replacement geofence (area ids). Omit to leave the geofence untouched.
 */
geofence?: Array<number>, };
