// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `PATCH /v4/areas/{id}`. Every field is optional: omitted
 * fields are left unchanged, and `null` clears an optional field. Mirrors the
 * create body minus `url_alias`, which is immutable.
 */
export type PatchAreaArgs = { name?: string, type?: string, 
/**
 * A string sets the description; `null` clears it; an omitted or blank
 * value leaves it unchanged.
 */
description?: string | null, 
/**
 * A new geometry. `null` is rejected: an area cannot lose its geometry
 * (and with it its bounding box).
 */
geo_json?: Record<string, unknown>, 
/**
 * A `YYYY-MM-DD` string sets the verification date (stored as
 * `verified:date`); `null` clears it; an omitted or blank value leaves it
 * unchanged.
 */
verified_at?: string | null, 
/**
 * Well-known contact channels keyed by bare channel name (e.g. `telegram`),
 * stored as `contact:<name>`. `null` removes a channel; omitted channels
 * are left unchanged. Channels outside `SUBMITTABLE_CONTACT_CHANNELS` are
 * silently ignored.
 */
contact?: Record<string, unknown | null>, };
