// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostNoteArgs = { lat: number, lon: number, text: string, 
/**
 * Icon discriminator, e.g. `notes`. Defaults to `notes` when omitted.
 */
icon?: string, public: boolean, };
