// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /v4/areas`.
 *
 * Generic area `tags` are abstracted away behind named fields instead of being
 * accepted verbatim. `contact` is the only free-form part and is filtered
 * through `SUBMITTABLE_CONTACT_CHANNELS`, so a caller can only ever set
 * known, non-sensitive tags.
 */
export type PostAreaArgs = { name: string, type: string, url_alias: string, geo_json: Record<string, unknown>, description?: string, 
/**
 * Last verification date as `YYYY-MM-DD`, stored as the `verified:date`
 * tag. A blank value is ignored.
 */
verified_at?: string, 
/**
 * Well-known contact channels keyed by bare channel name (e.g. `telegram`),
 * stored as `contact:<name>`. Channels outside
 * `SUBMITTABLE_CONTACT_CHANNELS` are silently ignored.
 */
contact?: Record<string, unknown>, };
