// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSearchResult = { id: number, name: string, roles: Array<string>, created_at: string, 
/**
 * Area ids the user is restricted to when acting as an event manager.
 * Empty means unrestricted (same meaning as on `GET /users/me`).
 */
geofence: Array<number>, npub?: string, };
